services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: symfony_php
    volumes:
      - ./www:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - DATABASE_URL=mysql://symfony:password@mysql:3306/symfony
    depends_on:
      - mysql
    networks:
      - symfony_network

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - symfony_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - symfony_network

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: symfony_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony_network

volumes:
  mysql_data:

networks:
  symfony_network:
    driver: bridge 